### ISSUE TITLE
[LOAD] when deleted the xml file and re-run the program, the display at bottom is wrong

### ISSUE THREAD

**Issue by peng229** [CS2103JAN2017-W14-B1/main#121]
When the file is not there, it should display the default data.

**Comment by vesaliE** [comment]
if the file is deleted, the display at the bottom means the new file will be saved at the given path.
if the file is deleted, save command will create the file unless the user wants to specify a new path

**Comment by vesaliE** [comment]
if the file is deleted, the file location shown in the status footer bar will be created unless otherwise specified by the user

**Comment by vesaliE** [comment]
The display at the bottom is for the save command not the load command

**Comment by vesaliE** [comment]
When file is not present, app displays default data
